steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Fetch credentials from Secret Manager'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching service account credentials from Secret Manager..."
        gcloud secrets versions access latest --secret="my-service-account-credentials" > /workspace/service_account.json
        echo "Credentials fetched successfully."

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Use credentials for gcloud commands'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/service_account.json'  # Set environment variable directly here
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Using service account credentials for gcloud command"
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        # Add any gcloud command that needs authentication here

  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mently-apps:latest'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mently-apps:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'mently-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mently-apps:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--allow-unauthenticated'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets=JWT_RESET_SECRET=JWT_RESET_SECRET:latest'
      - '--set-secrets=EMAIL_USER=EMAIL_USER:latest'
      - '--set-secrets=EMAIL_PASS=EMAIL_PASS:latest'
      - '--set-secrets=GCLOUD_PROJECT=GCLOUD_PROJECT:latest'
      - '--set-secrets=GCLOUD_BUCKET=GCLOUD_BUCKET:latest'
      - '--set-secrets=DB_NAME=DB_NAME:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=DB_HOST=DB_HOST:latest'
      - '--set-secrets=MODEL_URL=MODEL_URL:latest'
      - '--timeout=900s'

images:
  - 'gcr.io/$PROJECT_ID/mently-apps:latest'

options:
  logging: CLOUD_LOGGING_ONLY
